-- 网站数据 SQL
-- 生成时间: 2024-12-21 04:55:56
-- 编码: UTF-8

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

INSERT INTO `web_info` (`title`, `description`, `url`, `auth_level`, `create_time`) VALUES (N'DevSkyr – 程序“猿”的dev综合社区、云、数据、源代码', N'免费虚拟主机', 'https://www.devskyr.com/', 0, '2024-12-21 04:55:58');
INSERT INTO `web_info` (`title`, `description`, `url`, `auth_level`, `create_time`) VALUES (N'DevSkyr – 程序“猿”的dev综合社区、云、数据、源代码', N'免费虚拟主机', 'https://www.devskyr.com', 0, '2024-12-21 04:55:59');
INSERT INTO `web_info` (`title`, `description`, `url`, `auth_level`, `create_time`) VALUES (N'圈子 – DevSkyr', N'官网首页在线网盘高速免费圈子社区帮助中心关于我们软柠科技云服务文章文章商铺文档快讯圈子网址导航用户您有个重要的通知！一定要查看{{userData.name}}已认证文章评论关注粉丝￥{{role.user_data.money}}', 'https://www.devskyr.com/circle', 0, '2024-12-21 04:56:01');
INSERT INTO `web_info` (`title`, `description`, `url`, `auth_level`, `create_time`) VALUES (N'帮助中心 – DevSkyr', N'如果您在站点遇到了不懂的事情或疑问可以联系客服：fohui88（微信） QQ：122022099或3156914470 如迟迟不通过好友验证可联系在线客服，点此处【进入追溯客服】 如果您是有站点问题反…', 'https://www.devskyr.com/helppage', 0, '2024-12-21 04:56:03');
INSERT INTO `web_info` (`title`, `description`, `url`, `auth_level`, `create_time`) VALUES (N'关于我们 – DevSkyr', N'官网首页在线网盘高速免费圈子社区帮助中心关于我们软柠科技云服务文章文章商铺文档快讯圈子网址导航用户您有个重要的通知！一定要查看{{userData.name}}已认证文章评论关注粉丝￥{{role.user_data.money}}', 'https://www.devskyr.com/aboutus', 0, '2024-12-21 04:56:05');
INSERT INTO `web_info` (`title`, `description`, `url`, `auth_level`, `create_time`) VALUES (N'通知 – DevSkyr', N'官网首页在线网盘高速免费圈子社区帮助中心关于我们软柠科技云服务文章文章商铺文档快讯圈子网址导航用户您有个重要的通知！一定要查看{{userData.name}}已认证文章评论关注粉丝￥{{role.user_data.money}}', 'https://www.devskyr.com/message', 0, '2024-12-21 04:56:07');
INSERT INTO `web_info` (`title`, `description`, `url`, `auth_level`, `create_time`) VALUES (N'财富管理 – DevSkyr', N'官网首页在线网盘高速免费圈子社区帮助中心关于我们软柠科技云服务文章文章商铺文档快讯圈子网址导航用户您有个重要的通知！一定要查看{{userData.name}}已认证文章评论关注粉丝￥{{role.user_data.money}}', 'https://www.devskyr.com/gold', 0, '2024-12-21 04:56:08');
INSERT INTO `web_info` (`title`, `description`, `url`, `auth_level`, `create_time`) VALUES (N'我的任务 – DevSkyr', N'官网首页在线网盘高速免费圈子社区帮助中心关于我们软柠科技云服务文章文章商铺文档快讯圈子网址导航用户您有个重要的通知！一定要查看{{userData.name}}已认证文章评论关注粉丝￥{{role.user_data.money}}', 'https://www.devskyr.com/task', 0, '2024-12-21 04:56:10');
INSERT INTO `web_info` (`title`, `description`, `url`, `auth_level`, `create_time`) VALUES (N'私信 – DevSkyr', N'官网首页在线网盘高速免费圈子社区帮助中心关于我们软柠科技云服务文章文章商铺文档快讯圈子网址导航用户您有个重要的通知！一定要查看{{userData.name}}已认证文章评论关注粉丝￥{{role.user_data.money}}', 'https://www.devskyr.com/directmessage', 0, '2024-12-21 04:56:11');
INSERT INTO `web_info` (`title`, `description`, `url`, `auth_level`, `create_time`) VALUES (N'推广中心 – DevSkyr', N'官网首页在线网盘高速免费圈子社区帮助中心关于我们软柠科技云服务文章文章商铺文档快讯圈子网址导航用户您有个重要的通知！一定要查看{{userData.name}}已认证文章评论关注粉丝￥{{role.user_data.money}}', 'https://www.devskyr.com/distribution', 0, '2024-12-21 04:56:13');
INSERT INTO `web_info` (`title`, `description`, `url`, `auth_level`, `create_time`) VALUES (N'成为会员 – DevSkyr', N'官网首页在线网盘高速免费圈子社区帮助中心关于我们软柠科技云服务文章文章商铺文档快讯圈子网址导航用户您有个重要的通知！一定要查看{{userData.name}}已认证文章评论关注粉丝￥{{role.user_data.money}}', 'https://www.devskyr.com/vips', 0, '2024-12-21 04:56:15');
INSERT INTO `web_info` (`title`, `description`, `url`, `auth_level`, `create_time`) VALUES (N'认证服务 – DevSkyr', N'官网首页在线网盘高速免费圈子社区帮助中心关于我们软柠科技云服务文章文章商铺文档快讯圈子网址导航用户您有个重要的通知！一定要查看{{userData.name}}已认证文章评论关注粉丝￥{{role.user_data.money}}', 'https://www.devskyr.com/verify', 0, '2024-12-21 04:56:16');
INSERT INTO `web_info` (`title`, `description`, `url`, `auth_level`, `create_time`) VALUES (N'小黑屋 – DevSkyr', N'官网首页在线网盘高速免费圈子社区帮助中心关于我们软柠科技云服务文章文章商铺文档快讯圈子网址导航用户您有个重要的通知！一定要查看{{userData.name}}已认证文章评论关注粉丝￥{{role.user_data.money}}', 'https://www.devskyr.com/dark-room', 0, '2024-12-21 04:56:18');
INSERT INTO `web_info` (`title`, `description`, `url`, `auth_level`, `create_time`) VALUES (N'登录 ‹ DevSkyr — WordPress', N'登录基于 WordPress用户名或邮箱地址密码使用软柠账号登陆 记住我如果您没有账号或忘记密码，请返回至首页使用弹窗进行注册或修改密码', 'https://www.devskyr.com/wp-admin/', 0, '2024-12-21 04:56:20');
INSERT INTO `web_info` (`title`, `description`, `url`, `auth_level`, `create_time`) VALUES (N'摄影叙事 – DevSkyr', N'在这里交流您拍下的每一个时刻，可获得蜜雪冰城哦~', 'https://www.devskyr.com/circle/photo', 0, '2024-12-21 04:56:22');
INSERT INTO `web_info` (`title`, `description`, `url`, `auth_level`, `create_time`) VALUES (N'网站版本新升级（V12.5.71）查看最新更新消息 – DevSkyr', N'前言介绍 大家好，这里是“DevSkyr运维团队”本次文章是对新版本的介绍以及一些最新的说明；自2023年9月起，我们团队就一直处于频繁更新当中，只是为了能给大家带来最好的使用体验，在今年，也就是20…', 'https://www.devskyr.com/9021.html', 0, '2024-12-21 04:56:24');
INSERT INTO `web_info` (`title`, `description`, `url`, `auth_level`, `create_time`) VALUES (N'Xxiao王同学的基本信息 – DevSkyr', N'官网首页在线网盘高速免费圈子社区帮助中心关于我们软柠科技云服务文章文章商铺文档快讯圈子网址导航用户您有个重要的通知！一定要查看{{userData.name}}已认证文章评论关注粉丝￥{{role.user_data.money}}', 'https://www.devskyr.com/users/1', 0, '2024-12-21 04:56:25');
INSERT INTO `web_info` (`title`, `description`, `url`, `auth_level`, `create_time`) VALUES (N'线上正式运营预热-平台管理团队招人 – DevSkyr', N'我司自2018年建立起至今（2024年4月17日）一直属于半运营状态；包括但不限于测试、研发、管理、运营、合作、项目签约。现定期2024年7月19日开启全网正式运营（该期间作为完善管理团队、完善应用对…', 'https://www.devskyr.com/3231.html', 0, '2024-12-21 04:56:27');
INSERT INTO `web_info` (`title`, `description`, `url`, `auth_level`, `create_time`) VALUES (N'平台等级福利与新模式 – DevSkyr', N'等级相关规定与福利如下；我们将以可使用积分兑换服务器等方式进行管理；这是为了让用户自觉遵守平台规定，我们也会一点一点守护平台制度。 权限相关如下： ·发送私信发布文章发布评论发布快讯发布问答问答的回答…', 'https://www.devskyr.com/2462.html', 0, '2024-12-21 04:56:29');
INSERT INTO `web_info` (`title`, `description`, `url`, `auth_level`, `create_time`) VALUES (N'校园点餐订餐外卖跑腿Java源码 – DevSkyr', N'一个非常实用的校园外卖系统，基于 SpringBoot 和 Vue 的开发。这一系统源于黑马的外卖案例项目 经过站长的进一步改进和优化，提供了更丰富的功能和更高的可用性。 这个项目的架构设计非常有趣。…', 'https://www.devskyr.com/9688.html', 0, '2024-12-21 04:56:30');
INSERT INTO `web_info` (`title`, `description`, `url`, `auth_level`, `create_time`) VALUES (N'QBZ的基本信息 – DevSkyr', N'官网首页在线网盘高速免费圈子社区帮助中心关于我们软柠科技云服务文章文章商铺文档快讯圈子网址导航用户您有个重要的通知！一定要查看{{userData.name}}已认证文章评论关注粉丝￥{{role.user_data.money}}', 'https://www.devskyr.com/users/241', 0, '2024-12-21 04:56:32');
INSERT INTO `web_info` (`title`, `description`, `url`, `auth_level`, `create_time`) VALUES (N'全新紫色新UI数码盲盒系统源码/全开源无加密/附教程 – DevSkyr', N'全新紫色新UI数码盲盒系统源码/全开源无加密/附教程 前端uniapp+H5 后端FastAdmin框架 可打包成APP多端运行 亲测可用 测试运行环境：Nginx+PHP7.2+MySQ…', 'https://www.devskyr.com/9679.html', 0, '2024-12-21 04:56:34');
INSERT INTO `web_info` (`title`, `description`, `url`, `auth_level`, `create_time`) VALUES (N'免费领一年正版IObit Driver Booster Pro驱动安装神器激活码 – DevSkyr', N'今天分享一下 IObit Driver Booster Pro 驱动安装神器激活码，安装的时候，也就是上图所示，缙哥哥发现了有两个 IObit 系列软件的推广，这里记得点跳过，如果选择接受并安装，则会…', 'https://www.devskyr.com/9677.html', 0, '2024-12-21 04:56:35');
INSERT INTO `web_info` (`title`, `description`, `url`, `auth_level`, `create_time`) VALUES (N'Unity鼠标控制视角的理论与实践 – DevSkyr', N'本文作者:永柠网络科技 首席程序师-探花 (1)理论 欧拉角(Euler Angle)是可以表示3D空间中任何旋转的3个值，由莱昂哈德·欧拉(Leonhard Euler)在18世纪提出…', 'https://www.devskyr.com/9575.html', 0, '2024-12-21 04:56:37');
INSERT INTO `web_info` (`title`, `description`, `url`, `auth_level`, `create_time`) VALUES (N'永柠网络科技的基本信息 – DevSkyr', N'官网首页在线网盘高速免费圈子社区帮助中心关于我们软柠科技云服务文章文章商铺文档快讯圈子网址导航用户您有个重要的通知！一定要查看{{userData.name}}已认证文章评论关注粉丝￥{{role.user_data.money}}', 'https://www.devskyr.com/users/100014', 0, '2024-12-21 04:56:39');
INSERT INTO `web_info` (`title`, `description`, `url`, `auth_level`, `create_time`) VALUES (N'B2主题私信强提醒插件 – DevSkyr', N'大家好，又是我，废话连篇的我，前段时间在社区里发布过关于b2提醒的插件演示，很可惜的告诉大家，那个版本需要改好多文件，而且春哥只要已更新，代码就得重新做，个人能力有限，也确实找不到什么办法可以优化，但…', 'https://www.devskyr.com/9524.html', 0, '2024-12-21 04:56:40');
INSERT INTO `web_info` (`title`, `description`, `url`, `auth_level`, `create_time`) VALUES (N'WordPress多站共用一个用户数据表，实现用户在任何一站注册即可登录在任何一个站 – DevSkyr', N'首先我要讲一下关于这件事的经过，在很久很久以前（两年前）我就在想：“我们的网站即然都是WordPress，下面有这么多用户都在用着我们的一些产品，但是每到一个站点都要重新注册一个账号，这很痛苦，说实…', 'https://www.devskyr.com/9440.html', 0, '2024-12-21 04:56:42');
INSERT INTO `web_info` (`title`, `description`, `url`, `auth_level`, `create_time`) VALUES (N'针对近期整理总结的问题做出调整 – DevSkyr', N'我司平台在近日出现大量违反规定的信息，有人使用个人信息打广告（包括但不限于色情、博彩），同时部分用户（疑似机器人注册或注入）现已全部清空。在2024年10月14日晚23时44分网站进入风控状态（安全技…', 'https://www.devskyr.com/9253.html', 0, '2024-12-21 04:56:54');
INSERT INTO `web_info` (`title`, `description`, `url`, `auth_level`, `create_time`) VALUES (N'报道小妹的基本信息 – DevSkyr', N'官网首页在线网盘高速免费圈子社区帮助中心关于我们软柠科技云服务文章文章商铺文档快讯圈子网址导航用户您有个重要的通知！一定要查看{{userData.name}}已认证文章评论关注粉丝￥{{role.user_data.money}}', 'https://www.devskyr.com/users/671', 0, '2024-12-21 04:56:56');
INSERT INTO `web_info` (`title`, `description`, `url`, `auth_level`, `create_time`) VALUES (N'【公益报告】赞助公益项目！我们共同为各类行业实行零前期投入！ – DevSkyr', N'大家好，这里是“DevSkyr”的公益项目组，我们想向各位说一些事...自2021年我们建立了这个社区，虽说2023年6月才开始正式运营，但在运营前就已经确定了公益项目的开展，…', 'https://www.devskyr.com/9080.html', 0, '2024-12-21 04:56:58');
INSERT INTO `web_info` (`title`, `description`, `url`, `auth_level`, `create_time`) VALUES (N'拜年纪报名说明及参与事项 – DevSkyr', N'制作的起源 项目本身而言-拜年纪-是纯无营收项目，那么我们为什么要做？理由很简单，就是想做，我们不只是想做一个冰冷的赚钱公司，我们更希望和我们的客户，合作方，用户们“打成一片”，愉快的工作。2020年…', 'https://www.devskyr.com/9036.html', 0, '2024-12-21 04:56:59');
INSERT INTO `web_info` (`title`, `description`, `url`, `auth_level`, `create_time`) VALUES (N'软柠拜年纪的基本信息 – DevSkyr', N'官网首页在线网盘高速免费圈子社区帮助中心关于我们软柠科技云服务文章文章商铺文档快讯圈子网址导航用户您有个重要的通知！一定要查看{{userData.name}}已认证文章评论关注粉丝￥{{role.user_data.money}}', 'https://www.devskyr.com/users/635', 0, '2024-12-21 04:57:01');
INSERT INTO `web_info` (`title`, `description`, `url`, `auth_level`, `create_time`) VALUES (N'新的虚拟主机运营团队CoreCode及模式 – DevSkyr', N'免费产品运营相当耗费心情，遇上离谱用户更加头疼，请用户珍惜产品（免费虚拟主机运营满一周年） 针对数据库崩塌事件回应 自2024年7月16日起数据库开始强烈波动，至2024年8月19 日 23 时 19…', 'https://www.devskyr.com/9025.html', 0, '2024-12-21 04:57:03');
INSERT INTO `web_info` (`title`, `description`, `url`, `auth_level`, `create_time`) VALUES (N'蓝屏工具箱：插件商店开启系统工具新境界 – DevSkyr', N'蓝屏工具箱以其简洁大气的界面设计首先映入用户眼帘。4.0 版本采用的新一代 SUI3.0 界面，犹如一幅精美的画卷，将复杂的功能逻辑有序排列，既展现出强大的功能性，又不失简洁之美。用户无需在繁琐的菜单…', 'https://www.devskyr.com/8992.html', 0, '2024-12-21 04:57:04');
INSERT INTO `web_info` (`title`, `description`, `url`, `auth_level`, `create_time`) VALUES (N'makotowu的基本信息 – DevSkyr', N'官网首页在线网盘高速免费圈子社区帮助中心关于我们软柠科技云服务文章文章商铺文档快讯圈子网址导航用户您有个重要的通知！一定要查看{{userData.name}}已认证文章评论关注粉丝￥{{role.user_data.money}}', 'https://www.devskyr.com/users/630', 0, '2024-12-21 04:57:06');
INSERT INTO `web_info` (`title`, `description`, `url`, `auth_level`, `create_time`) VALUES (N'公司业务框架变更 – DevSkyr', N'上海枫汇网络科技有限公司；以下简称“我司或本公司”将在今日将部分运营项目做出清算（包括但不限于转交、解散、移除），同时将会与我司开办的第二主体“杭州软柠科技有限公司”进行项目对接，日后枫汇公司将作为系…', 'https://www.devskyr.com/8873.html', 0, '2024-12-21 04:57:08');
INSERT INTO `web_info` (`title`, `description`, `url`, `auth_level`, `create_time`) VALUES (N'搭建一个mc官网，源码免费！送主机，送域名！ – DevSkyr', N'实在太懒了，文本过段时间来写，还是去看bilibili的视频吧，如果看不懂可以联系我，免费帮你弄！ 进群加微信13766555693 下面可以下载网站源码。 免费主机：DevSkyr Cloud（滴维…', 'https://www.devskyr.com/8849.html', 0, '2024-12-21 04:57:09');
INSERT INTO `web_info` (`title`, `description`, `url`, `auth_level`, `create_time`) VALUES (N'宣传本站得2h2g服务器！下阶返利！ – DevSkyr', N'活动即日起生效；用户可以使用任何方式，例如：返利优惠、搭建源码推荐服务器、广告位推荐等方式获得10位以上的下阶用户即可获得2h2g的服务器为期1个月，每多10个下阶用户即可多免费续1个月，下阶用户在我…', 'https://www.devskyr.com/8806.html', 0, '2024-12-21 04:57:11');
INSERT INTO `web_info` (`title`, `description`, `url`, `auth_level`, `create_time`) VALUES (N'写文章 – DevSkyr', N'官网首页在线网盘高速免费圈子社区帮助中心关于我们软柠科技云服务文章文章商铺文档快讯圈子网址导航用户您有个重要的通知！一定要查看{{userData.name}}已认证文章评论关注粉丝￥{{role.user_data.money}}', 'https://www.devskyr.com/write', 0, '2024-12-21 04:57:12');
INSERT INTO `web_info` (`title`, `description`, `url`, `auth_level`, `create_time`) VALUES (N'问答 – DevSkyr', N'官网首页在线网盘高速免费圈子社区帮助中心关于我们软柠科技云服务文章文章商铺文档快讯圈子网址导航用户您有个重要的通知！一定要查看{{userData.name}}已认证文章评论关注粉丝￥{{role.user_data.money}}', 'https://www.devskyr.com/ask', 0, '2024-12-21 04:57:14');
INSERT INTO `web_info` (`title`, `description`, `url`, `auth_level`, `create_time`) VALUES (N'供求信息 – DevSkyr', N'官网首页在线网盘高速免费圈子社区帮助中心关于我们软柠科技云服务文章文章商铺文档快讯圈子网址导航用户您有个重要的通知！一定要查看{{userData.name}}已认证文章评论关注粉丝￥{{role.user_data.money}}', 'https://www.devskyr.com/infomation', 0, '2024-12-21 04:57:16');
INSERT INTO `web_info` (`title`, `description`, `url`, `auth_level`, `create_time`) VALUES (N'隐私政策及用户协议 – DevSkyr', N'DevSkyr用户协议 更新日期：2023年9月18日 生效日期：2023年10月26日 1、导言欢迎您使用“DevSkyr”及相关服务！ “DevSkyr”及相关服务，系指上海枫汇网络科技有限公司（…', 'https://www.devskyr.com/privacy-policy', 0, '2024-12-21 04:57:17');
INSERT INTO `web_info` (`title`, `description`, `url`, `auth_level`, `create_time`) VALUES (N'专题中心 – DevSkyr', N'官网首页在线网盘高速免费圈子社区帮助中心关于我们软柠科技云服务文章文章商铺文档快讯圈子网址导航用户您有个重要的通知！一定要查看{{userData.name}}已认证文章评论关注粉丝￥{{role.user_data.money}}', 'https://www.devskyr.com/collection', 0, '2024-12-21 04:57:19');

SET FOREIGN_KEY_CHECKS = 1;
